-- 서브쿼리로 풀이
-- NAME이 Milk인 CART_ID 테이블에도 존재하고
-- NAME이 Yogurt인 CART_ID 테이블에도 존재하는 CART_ID를 중복 없이 조회
SELECT DISTINCT(CART_ID) FROM CART_PRODUCTS
WHERE CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS
WHERE NAME = 'Milk') AND
CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS
WHERE NAME = 'Yogurt')
ORDER BY CART_ID;

-- GROUP BY를 이용한 풀이
SELECT CART_ID
FROM CART_PRODUCTS cp
WHERE 
    NAME = 'Milk' OR 
    NAME = 'Yogurt'
GROUP BY CART_ID HAVING COUNT(distinct(NAME)) > 1
ORDER BY CART_ID;

-- INNER JOIN 이용한 풀이
SELECT DISTICT M.CART_ID
FROM CART_PRODUCTS M INNER JOIN CART_PRODUCTS Y
ON M.CART_ID = Y.CART_ID
WHERE M.NAME LIKE '%Milk%' AND Y.NAME LIKE '%Yogurt%';